### ISSUE TITLE
Add RemitGuru implementation

### ISSUE THREAD

**Issue by siddharthgoel88** [siddharthgoel88/xrates#8]
An example curl request for it is as follows : 

curl 'http://www.remitguru.com/transfer/jsp/getQTStatistics.jsp' -H 'Origin: http://www.remitguru.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,hi;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36' -H 'Content-type: application/x-www-form-urlencoded' -H 'Accept: _/_' -H 'Referer: http://www.remitguru.com/' -H 'Cookie: JSESSIONID=6D03E2BFB55E12FCD5522925EDF7A7D0; __utma=161803967.1062202356.1437661741.1437661741.1437661741.1; __utmc=161803967; __utmz=161803967.1437661741.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)' -H 'Connection: keep-alive' --data 'amountTransfer=7000&corridor=SG~SGD~IN~INR&sendMode=CIP-NORMAL' --compressed

**Comment by harshulgandhi** [comment]
Added implementation to fetch remit guru conversion rates.
