### ISSUE TITLE
Add currency exchange matrix

### ISSUE THREAD

**Issue by harshulgandhi** [siddharthgoel88/xrates#9]

**Comment by harshulgandhi** [comment]
Added currency exchange matrix. Tested with different currency combination inputs for SGD and INR.

**Comment by harshulgandhi** [comment]
Need to make matrix generation generic - hard coded right now

**Comment by siddharthgoel88** [comment]
Changed currency matrix to Map. See https://github.com/siddharthgoel88/xrates/commit/7b46a50f48b9faf474a3da9b69f1a969dc44eea8
